title: Gagandeep Singh Kalra
description: Senior Software Engineer | Go, Python, TypeScript — 7 years designing event-driven microservices and cloud-native platforms
url: "https://igagankalra.github.io"

# Social sharing image
image: /pexels-markusspiske-193350.jpg

# These plugins are officially supported and will not break your build!
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap